- name: ensure system dependencies are installed and up to date
  raw: apt-get update && apt-get install -y python unattended-upgrades

#- name: ensure system is updated
#  shell: apt-get -y upgrade
#  when: env != 'development'
#
#- name: ensure unattended upgrades are running
#  copy:
#    content: |
#      APT::Periodic::Update-Package-Lists "1";
#      APT::Periodic::Download-Upgradeable-Packages "1";
#      APT::Periodic::AutocleanInterval "7";
#      APT::Periodic::Unattended-Upgrade "1";
#    dest: /etc/apt/apt.conf.d/10periodic

- name: install apt packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - build-essential # to build software
    - git # to clone repositories
    - htmldoc # to generate pdfs from html
    - pdftk # to operate on pdfs
    - nginx # to serve traffic
    - php7.0-fpm # to connect nginx and php
    - php7.0-pgsql # to allow php to connect to postgres
    - php7.0-curl # to make external web requests w/ php
    - php-fpdf # to generate pdfs w/ php
    - php7.0-xml # to parse xml w/ php
    - php7.0-gd # for image manipulation
