- name: ensure ssh agent socket environment variable persists when sudoing
  lineinfile:
    dest: /etc/sudoers
    state: present
    insertafter: "^Defaults"
    line: "Defaults\tenv_keep += \"SSH_AUTH_SOCK\""
    validate: "visudo -cf %s"

- name: ensure github.com is a known host
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    state: present
    create: yes
    regexp: "^github\\.com"
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
