Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.define "vagrant"
  config.vm.synced_folder "src", "/mnt"
  config.vm.network "private_network", ip: "10.10.10.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  config.hostsupdater.aliases = [
    'metronet.loc',
    'wk.loc'
  ]
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/vagrant.yml"
  end
end
