- name: ensure apt key is present
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: ensure apt ppa is present
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
    state: present

- name: ensure binaries are installed
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - postgresql-9.6 # for data persistence
    - postgresql-client-9.6 # for connecting to database

- name: ensure postgresql security is disabled in development
  copy:
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    content: |
      local all postgres trust
      local all all trust
      host all all 0.0.0.0/0 trust
      host all all 127.0.0.1/32 trust
      host all all ::1/128 trust
    force: yes
  when: env != 'production'

- name: ensure service is running and will start at boot
  service:
    name: postgresql
    state: restarted
    enabled: yes
    use: service

- name: ensure .pgpass is in place for backup authentication
  template:
    src: .pgpass.j2
    dest: /root/.pgpass
    mode: 0600
  when: env == 'production'

- name: ensure backup script is in place
  template:
    src: backup.sh.j2
    dest: /root/backup.sh
    mode: 0700
  when: env == 'production'

- name: ensure backup is run hourly
  cron:
    name: backup
    minute: 0
    job: /root/backup.sh
    cron_file: backup
    user: root
  when: env == 'production'
