url:
  www: http://our-365.com
  cdn: http://cdn.our-365.com

db:
  adapter: postgres
  database: our-365
  user: tkellen

email:
  to: team@our-365.com
  from: team@our-365.com

dailyshare:
  start: 2012-01-01

disqus:
  shortname: ourthreesixtyfiveproject

seo:
  title: our 365 project
  description: Six friends.  Two states.  One picture each.  Every day.  We’re doing it to practice discipline; we’re doing it to become better photographers; we're doing it to document our lives, and most of all, we’re doing it to keep in touch with our friends.  This is year one, and there will be 2,190 photographs when it's over.

